unit uhershey;

{ uhershey: Hershey vector-stroke font engraver (plan Phase 16). Pure/LCL-free
  g-code text generator, ported from LaserGRBL's real
  Hershey/Hershey.cs (confirmed 343 lines, `hor`/`ver` glyph tables +
  CreateString/MeasureString/ApplyOffset).

  Scope note (disclosed): only the `hor` (horizontal-text) glyph table is
  ported - 95 entries, ASCII 32 'space' through 126 '~', `c - 32` indexed,
  in hershey_data.inc. The reference also ships a `ver` (vertical-text)
  variant; Phase 16's own "Done" bar ("a labeled test grid renders with
  legible text strokes") only needs horizontal text, so `ver` is a
  deliberate, disclosed deferral, not a silent drop.

  hershey_data.inc's HersheyChars was generated by a one-off extraction
  script (not hand-retyped) directly from the real Hershey.cs source, to
  avoid transcription errors in ~300 lines of floating-point stroke
  coordinates; each glyph's own token fragments (mirrors this app's own
  g-code line shape: G0X../Y.., M3, G1X../Y.., M5) are flattened into one
  '|'-delimited string per glyph (a flat array literal) rather than a
  jagged array-of-arrays, and split back into tokens at load time.

  ApplyOffsetToken below is a hand-written scanner for the `[XY]-?\d+(\.\d+)?`
  coordinate tokens the real ApplyOffset finds via .NET regex - same
  approach as usvgpath.pas's own hand-written path-data tokenizer, not a
  regex library dependency. }

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

type
  TStringArray = array of string;

// HersheyText: mirrors Hershey.cs's real CreateString - builds one g-code
// line per stroke, laid out left-to-right and centered at
// (ACenterX, ACenterY). ATurnOnCmd is substituted verbatim for each glyph's
// "M3" placeholder (this app's own already-built laser-on command, e.g.
// from TLaserControlFrame's TestFirePower - mirrors the real `ton`
// parameter, which the C# caller likewise builds elsewhere). Returns a new
// TStringList the caller owns.
function HersheyText(const AText: string; ACenterX, ACenterY: Double;
  const ATurnOnCmd: string): TStringList;

// HersheyMeasure: mirrors Hershey.cs's real MeasureString - the rendered
// width/height of AText, with no g-code generated, so a caller can lay out
// several labels before engraving any of them.
procedure HersheyMeasure(const AText: string; out ASizeX, ASizeY: Double);

implementation

{$I hershey_data.inc}

const
  SPACING = 0.3; // spbwl in the real Hershey.cs

var
  GInvFS: TFormatSettings; // '.' decimal separator, regardless of locale

function SplitGlyph(AIndex: Integer): TStringArray;
var
  parts: TStringList;
  i: Integer;
begin
  parts := TStringList.Create;
  try
    parts.Delimiter := '|';
    parts.StrictDelimiter := True;
    parts.DelimitedText := HersheyChars[AIndex];
    SetLength(Result, parts.Count);
    for i := 0 to parts.Count - 1 do
      Result[i] := parts[i];
  finally
    parts.Free;
  end;
end;

// ApplyOffsetToken: shifts every X/Y coordinate found in AToken by
// AXOffset/AYOffset, tracking the glyph's own min/max per axis (the real
// ApplyOffset's sizeX/sizeY = maxX-minX / maxY-minY, seeded at 0 like the
// C#, so a glyph whose own coordinates are all >= 0 measures as its own
// largest coordinate - true of every real hor[] entry).
function ApplyOffsetToken(const AToken: string; AXOffset, AYOffset: Double;
  var AMaxX, AMinX, AMaxY, AMinY: Double): string;
var
  i, numStart: Integer;
  axis: Char;
  numStr: string;
  value: Double;
begin
  Result := '';
  i := 1;
  while i <= Length(AToken) do
  begin
    if (AToken[i] = 'X') or (AToken[i] = 'Y') then
    begin
      axis := AToken[i];
      numStart := i + 1;
      i := numStart;
      if (i <= Length(AToken)) and (AToken[i] = '-') then Inc(i);
      while (i <= Length(AToken)) and (AToken[i] in ['0'..'9', '.']) do Inc(i);
      if i > numStart then
      begin
        numStr := Copy(AToken, numStart, i - numStart);
        value := StrToFloat(numStr, GInvFS);
        if axis = 'X' then
        begin
          if value > AMaxX then AMaxX := value;
          if value < AMinX then AMinX := value;
          value := value + AXOffset;
        end
        else
        begin
          if value > AMaxY then AMaxY := value;
          if value < AMinY then AMinY := value;
          value := value + AYOffset;
        end;
        Result := Result + axis + FormatFloat('0.###', value, GInvFS);
      end
      else
        Result := Result + axis;
    end
    else
    begin
      Result := Result + AToken[i];
      Inc(i);
    end;
  end;
end;

function ApplyOffsetGlyph(const ATokens: TStringArray; AXOffset, AYOffset: Double;
  out ASizeX, ASizeY: Double): TStringArray;
var
  i: Integer;
  maxX, minX, maxY, minY: Double;
begin
  maxX := 0; minX := 0; maxY := 0; minY := 0;
  SetLength(Result, Length(ATokens));
  for i := 0 to High(ATokens) do
    Result[i] := ApplyOffsetToken(ATokens[i], AXOffset, AYOffset, maxX, minX, maxY, minY);
  ASizeX := maxX - minX;
  ASizeY := maxY - minY;
end;

procedure HersheyMeasure(const AText: string; out ASizeX, ASizeY: Double);
var
  i: Integer;
  c: Char;
  glyph: TStringArray;
  gSizeX, gSizeY: Double;
begin
  ASizeX := 0;
  ASizeY := 0;
  for i := 1 to Length(AText) do
  begin
    c := AText[i];
    if (c >= #32) and (c <= #126) then
    begin
      glyph := SplitGlyph(Ord(c) - 32);
      ApplyOffsetGlyph(glyph, 0, 0, gSizeX, gSizeY);
      ASizeX := ASizeX + gSizeX;
      if gSizeY > ASizeY then ASizeY := gSizeY;
      if i < Length(AText) then
        ASizeX := ASizeX + SPACING;
    end;
  end;
end;

function HersheyText(const AText: string; ACenterX, ACenterY: Double;
  const ATurnOnCmd: string): TStringList;
var
  i, j: Integer;
  c: Char;
  glyph, offsetGlyph: TStringArray;
  gSizeX, gSizeY, sizeX, sizeY, oX, oY: Double;
  cmd: string;
begin
  Result := TStringList.Create;
  HersheyMeasure(AText, sizeX, sizeY);
  sizeY := 2; // horizontal orientation fixed line height - mirrors the real
              // `if (horiz) sizeY = 2;` in Hershey.cs's CreateString
  oX := ACenterX - sizeX / 2;
  oY := ACenterY - sizeY / 2;

  for i := 1 to Length(AText) do
  begin
    c := AText[i];
    if (c >= #32) and (c <= #126) then
    begin
      glyph := SplitGlyph(Ord(c) - 32);
      offsetGlyph := ApplyOffsetGlyph(glyph, oX, oY, gSizeX, gSizeY);
      for j := 0 to High(offsetGlyph) do
      begin
        cmd := StringReplace(offsetGlyph[j], 'M3', ATurnOnCmd, [rfReplaceAll]);
        Result.Add(cmd);
      end;
      Result.Add('M5');
      oX := oX + gSizeX + SPACING;
    end;
  end;
end;

initialization
  GInvFS := DefaultFormatSettings;
  GInvFS.DecimalSeparator := '.';

end.
