unit uregistrationholes;

{ uregistrationholes: plan Phase 40 - drills a small, explicit set of
  registration/tooling holes at user-given board-relative XY positions,
  so a double-sided PCB job can be flipped around dowel pins pushed
  through those same holes and have the second side's toolpath land in
  the physically correct spot. CNC-only (a laser can't drill a real hole
  a dowel pin fits into). Reuses the exact per-hole peck-drill cycle
  uspoilboard.pas's own AppendHolesGCode already established (G0 XY,
  peck-loop G1Z/G0Z with full retract for chip clearance, final retract)
  - same GRBL-portable, no-canned-cycles approach, just walking explicit
  points instead of a computed grid. }

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Math, ui18n;

type
  TRegistrationPoint = record
    X, Y: Double;
  end;
  TRegistrationPointArray = array of TRegistrationPoint;

  TRegistrationHoleConfig = record
    HoleDiameter: Double;   // informational only, same convention as
                             // uspoilboard.pas's own HoleDiameter - drives
                             // no geometry here, just documents which bit
                             // to load (straight plunge, no boring).
    DrillDepth: Double;     // mm, positive
    PeckDepth: Double;      // 0 or >= DrillDepth = single plunge, no pecking
    PlungeRate: Double;     // mm/min
    SafeZ: Double;          // mm, retract height
    SpindleRPM: Integer;    // 0 = don't emit S/M3 (assume already running)
  end;

  EGenerateError = class(Exception);

procedure ValidateRegistrationConfig(const ACfg: TRegistrationHoleConfig);

{ AppendRegistrationHolesGCode: drills one hole per APoints entry, in
  array order (the caller decides the order - typically just "point 0,
  then point 1", since there are usually only two). Raises
  EGenerateError (ALines left untouched) if ACfg is not physically
  valid. }
procedure AppendRegistrationHolesGCode(const APoints: TRegistrationPointArray;
  const ACfg: TRegistrationHoleConfig; ALines: TStrings);

implementation

var
  GInvFS: TFormatSettings;

procedure ValidateRegistrationConfig(const ACfg: TRegistrationHoleConfig);
begin
  if ACfg.DrillDepth <= 0 then
    raise EGenerateError.Create(T('Drill depth must be positive.'));
  if ACfg.PlungeRate <= 0 then
    raise EGenerateError.Create(T('Plunge rate must be positive.'));
end;

procedure AppendRegistrationHolesGCode(const APoints: TRegistrationPointArray;
  const ACfg: TRegistrationHoleConfig; ALines: TStrings);
var
  i: Integer;
  peckDepth, currentDepth: Double;
begin
  ValidateRegistrationConfig(ACfg);
  if Length(APoints) = 0 then Exit;

  peckDepth := ACfg.PeckDepth;
  if (peckDepth <= 0) or (peckDepth >= ACfg.DrillDepth) then
    peckDepth := ACfg.DrillDepth;

  ALines.Add('(Registration holes generated by GRBL-Controller-Sender)');
  ALines.Add(Format('(hole diameter %.2f mm - use a bit of this diameter, straight plunge, no boring)',
    [ACfg.HoleDiameter], GInvFS));
  ALines.Add('G21');
  ALines.Add('G90');
  ALines.Add(Format('G0Z%.4f', [ACfg.SafeZ], GInvFS));
  if ACfg.SpindleRPM > 0 then
    ALines.Add(Format('M3S%d', [ACfg.SpindleRPM], GInvFS));

  for i := 0 to High(APoints) do
  begin
    ALines.Add(Format('(--- Registration hole %d/%d ---)', [i + 1, Length(APoints)]));
    ALines.Add(Format('G0X%.4fY%.4f', [APoints[i].X, APoints[i].Y], GInvFS));
    currentDepth := 0;
    while currentDepth < ACfg.DrillDepth - 1e-6 do
    begin
      currentDepth := Min(currentDepth + peckDepth, ACfg.DrillDepth);
      ALines.Add(Format('G1Z%.4fF%g', [-currentDepth, ACfg.PlungeRate], GInvFS));
      if currentDepth < ACfg.DrillDepth - 1e-6 then
        ALines.Add(Format('G0Z%.4f', [ACfg.SafeZ], GInvFS)); // peck: full retract for chip clearance
    end;
    ALines.Add(Format('G0Z%.4f', [ACfg.SafeZ], GInvFS));
  end;

  if ACfg.SpindleRPM > 0 then
    ALines.Add('M5');
  ALines.Add('M30');
end;

initialization
  GInvFS := DefaultFormatSettings;
  GInvFS.DecimalSeparator := '.';

end.
